config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'restaurants', to: 'restaurants#index'
  # get 'new', to: 'restaurants#new'
  # post 'new', to: 'restaurants#new'
  # get 'show', to: 'restaurants#show'

  resources :restaurants, only: [:index, :new, :create, :show] do
    # Custom routes relating to restaurants
    resources :reviews, only: [:new, :create]

    # end
  end

  # resources :reviews, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  category = ["chinese", "italian", "japanese", "french", "belgian"]

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: category }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  rating = [0, 1, 2, 3, 4, 5]

  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: rating }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # GET /restaurants/1
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

    # Only allow a trusted parameter "white list" through.
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    # Find the restaurant instance from the id in the params
    @restaurant = Restaurant.find(params[:restaurant_id])
    # Create a blank review for the empty form
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    # Associate my review together with my restaurant
    @review.restaurant = @restaurant
    if @review.save
      # Success
      redirect_to restaurant_path(@restaurant)
    else
      # Failure
      render :new
    end
  end

  def destroy
    # NOT NESTED
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All of your Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= restaurant.name %>
      <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary"%>
      <%= link_to "Add Review", new_restaurant_review_path(restaurant), class: "btn btn-primary"%>
  </li>
 <% end %>
</ul>

app/views/restaurants/show.html.erb
<h1>Name: <%= @restaurant.name %></h1>

<h3>Style: <%= @restaurant.category.capitalize%></h3>

<h4>Address: <%= @restaurant.address%></h4>

<p>Telephone: <%= @restaurant.phone_number%></p>

<h3>Reviews</h3>


  <ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %>
        <%= review.rating %></li>
  <% end %>
</ul>


<h3>Add a Review below: </h3>
<%= link_to "Add Review", new_restaurant_review_path(@restaurant), class: "btn btn-primary"%>

app/views/reviews/new.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
<!--   <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %> -->

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>